name: my_environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - napari=0.4.18
  - jupyter
  - scikit-learn
  - matplotlib
  - vigra
  - opencv
  - geopandas
  - h5py
  - mlxtend
  
